# Generated by Django 4.2.20 on 2025-09-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0012_auto_20240820_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doi', models.CharField(max_length=1024)),
                ('cite', models.TextField()),
            ],
        ),
    ]
