# Generated by Django 4.2.20 on 2025-10-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0013_citation'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='total_size',
            field=models.FloatField(default=0.0),
        ),
    ]
