# Generated by Django 4.2.20 on 2025-10-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0014_collection_total_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='total_size_with_ar',
            field=models.FloatField(default=0.0),
        ),
    ]
