# Generated by Django 4.2.20 on 2025-11-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0015_collection_total_size_with_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='cancer_type',
            field=models.TextField(null=True),
        ),
    ]
