# Generated by Django 4.2.20 on 2025-12-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0016_alter_collection_cancer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='license',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
