# Generated by Django 4.2.20 on 2026-01-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0017_collection_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_type',
            field=models.CharField(choices=[('A', 'Analysis Result'), ('O', 'Original Collection')], default='O', max_length=1),
        ),
    ]
