# Generated by Django 4.2.20 on 2026-04-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0018_alter_collection_collection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
