# Generated by Django 4.2.30 on 2026-10-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0019_alter_collection_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
